# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfd221f705a6f787daa445dc0a71229a"
name = "contact-app"
application_url = "https://psychiatry-trout-deleted-accurate.trycloudflare.com"
embedded = true
handle = "contact-app-7"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://psychiatry-trout-deleted-accurate.trycloudflare.com/auth/callback", "https://psychiatry-trout-deleted-accurate.trycloudflare.com/auth/shopify/callback", "https://psychiatry-trout-deleted-accurate.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
